--- 
title: "Statistical Modeling of High Dimensional Counts"
author: "Michael I. Love"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: "This book covers some basic routines for statistical modeling of high dimensional count data in using R/Bioconductor."
---

# About this online book {-}

This online book is a chapter of a physical book about RNA Bioinformatics.

Here I will describe how count data, as often arises in RNA sequencing (RNA-seq) 
experiments, can be modeled using count distributions, as well as how 
nonparametric methods can be used to analyze count data. The book will 
cover basic routines for performing data input, scaling/normalization, 
visualization, and statistical testing to determine sets of features
where the counts reflect differences in expression across samples.
The final section will cover limitations of the methods presented and
extensions.

The code in this book includes the basic routines that can be found
in software vignettes of various Bioconductor packages, including
[tximeta](https://bioconductor.org/packages/tximeta), 
[DESeq2](https://bioconductor.org/packages/DESeq2), and 
[fishpond](https://bioconductor.org/packages/fishpond). 
Please see those package vignettes for further details. 
Any specific questions about Bioconductor software should be posted 
to the Bioconductor support site:

* <https://support.bioconductor.org>

There are also two published workflows that are related to the 
analysis steps and packages described here, but which explore 
different directions. These workflows are hosted on the Bioconductor
workflow site, and checked regularly to ensure they build correctly 
and without error:

* [rnaseqGene](https://bioconductor.org/packages/rnaseqGene) - gene-level exploratory analysis and differential expression [@Love2015]
* [rnaseqDTU](https://bioconductor.org/packages/rnaseqDTU) - differential transcript usage [@Love2018]
