# Quantification {#quantification}

The first step in 

* Salmon [@Patro2017]
* tximeta [@Love2019]
* Alevin [@Srivastava2019]

```{r sysdir}
dir <- system.file("extdata", package="oct4")
list.files(dir)
```

```{r coldata}
library(readr)
library(dplyr)
coldata <- read_csv(file.path(dir,"coldata.csv"))
coldata <- coldata %>% 
  mutate(line=factor(line, levels=c("OCT4","BRG1")),
         condition=factor(condition, levels=c("untrt","trt")),
         files=file.path(dir, "quants", names, "quant.sf.gz"))
```

```{r file-exists}
all(file.exists(coldata$files))
```

```{r tximeta, cache=TRUE}
library(tximeta)
suppressPackageStartupMessages(library(SummarizedExperiment))
se <- tximeta(coldata, dropInfReps=TRUE)
```

```{r look-se}
assayNames(se)
rowRanges(se)
```

```{r summarize, cache=TRUE}
gse <- summarizeToGene(se)
```

```{r ranges}
rowRanges(gse)
x <- GRanges("chr1", IRanges(10e6, 11e6))
gse[gse %over% x, ]
gse[, gse$line == "OCT4"]
```

```{r addids}
library(org.Mm.eg.db)
gse <- addIds(gse, "SYMBOL", gene=TRUE)
```
