# Transcript level {#transcripts}

Here is some more text

* Uncertainty
* DTU

[@Li2011]

[@Zhu2019]

[@Storey2003]

[@Alasoo2018]

[@Love2016Modeling]

[@Nowicka2016]

[@VanDenBerge2017]

[@Soneson2016]

[@Anders2012]

```{r sysdir2}
dir <- system.file("extdata", package="macrophage")
list.files(dir)
```

```{r coldata2}
library(readr)
library(dplyr)
coldata <- read_csv(file.path(dir,"coldata.csv"))
coldata <- coldata %>% 
  dplyr::select(names, id=sample_id, line=line_id, condition=condition_name) %>%
  mutate(line=factor(line),
         condition=factor(condition, levels=c("naive","IFNg","SL1344","IFNg_SL1344")),
         files=file.path(dir, "quants", names, "quant.sf.gz"))
```

```{r filter}
coldata <- coldata %>% filter(condition %in% c("naive","IFNg"))
coldata$condition <- droplevels(coldata$condition)
```

```{r file-exists2}
all(file.exists(coldata$files))
```

```{r tximeta2, cache=TRUE}
library(tximeta)
suppressPackageStartupMessages(library(SummarizedExperiment))
y <- tximeta(coldata)
```

```{r sub-y}
y <- y[seqnames(y) == "chr1",]
```

```{r fishpond-scale-label}
library(fishpond)
y <- scaleInfReps(y, quiet=TRUE)
y <- labelKeep(y)
y <- y[mcols(y)$keep,]
```

```{r swish}
set.seed(1)
y <- swish(y, x="condition", pair="line", quiet=TRUE)
```

```{r swish-sig}
names(mcols(y))
table(mcols(y)$qvalue < .05)
```

```{r swish-hist}
hist(mcols(y)$pvalue, col="grey")
```

```{r swish-ma}
plotMASwish(y, alpha=.05)
```

```{r swish-counts}
idx <- with(mcols(y), which(pvalue < .05 & log2FC > 4))
plotInfReps(y, idx[1], x="condition", cov="line", xaxis=FALSE)
```
